export const simpleTableModules = [
  { name: 'machineInfo', component: 'keyValueList', heading: 'General Info', moduleName: 'general_info' },
  { name: 'ipAddresses', component: 'dataTable', heading: 'IP Addresses', moduleName: 'ip_addresses' },
  { name: 'ramIntensiveProcesses', component: 'dataTable', heading: 'RAM Processes', moduleName: 'ram_intensive_processes' },
  { name: 'cpuIntensiveProcesses', component: 'dataTable', heading: 'CPU Processes', moduleName: 'cpu_intensive_processes' },
  { name: 'dockerProcesses', component: 'dataTable', heading: 'Docker Processes', moduleName: 'docker_processes' },
  { name: 'networkConnections', component: 'dataTable', heading: 'Network Connections', moduleName: 'network_connections' },
  { name: 'serverAccounts', component: 'dataTable', heading: 'Accounts', moduleName: 'user_accounts' },
  { name: 'loggedInAccounts', component: 'dataTable', heading: 'Logged In Accounts', moduleName: 'logged_in_users' },
  { name: 'recentLogins', component: 'dataTable', heading: 'Recent Logins', moduleName: 'recent_account_logins' },
  { name: 'arpCacheTable', component: 'dataTable', heading: 'ARP Cache', moduleName: 'arp_cache' },
  { name: 'commonApplications', component: 'dataTable', heading: 'Common Applications', moduleName: 'common_applications' },
  { name: 'pingSpeeds', component: 'dataTable', heading: 'Ping Speeds', moduleName: 'ping' },
  { name: 'bandwidth', component: 'dataTable', heading: 'Bandwidth', moduleName: 'bandwidth' },
  { name: 'swapUsage', component: 'dataTable', heading: 'Swap Usage', moduleName: 'swap' },
  { name: 'memcached', component: 'keyValueList', heading: 'Memcached', moduleName: 'memcached' },
  { name: 'redis', component: 'keyValueList', heading: 'Redis', moduleName: 'redis' },
  { name: 'pm2', component: 'dataTable', heading: 'PM2', moduleName: 'pm2_stats' },
  { name: 'memoryInfo', component: 'keyValueList', heading: 'Memory Info', moduleName: 'memory_info' },
  { name: 'cpuInfo', component: 'keyValueList', heading: 'CPU Info', moduleName: 'cpu_info' },
  { name: 'ioStats', component: 'dataTable', heading: 'IO Stats', moduleName: 'io_stats' },
  { name: 'scheduledCrons', component: 'dataTable', heading: 'Scheduled Crons', moduleName: 'scheduled_crons' },
  { name: 'cronHistory', component: 'dataTable', heading: 'Cron History', moduleName: 'cron_history' },
];
